version: 2.1

orbs:
  ruby: circleci/ruby@1.0.5
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
      - image: circleci/postgres:9.5-alpine # database image
        environment: # environment variables for database
          POSTGRES_USER: stone
          POSTGRES_DB: stone_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: stone
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test

  deploy:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Deploy if tests pass and branch is Master
          command: bundle exec cap production deploy

workflows:
   version: 2
   build-and-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only deploy once build job has completed
           filters:
             branches:
               only: master
